### PR TITLE
Made dest folder optional and removed superfluous dl command

### PR DESCRIPTION
**Pull request by letsgetrandy**
I removed the `dl` command. If there's only one command, why not just make it the default behavior?

And now, if a second argument is not specified, it will just default to the current directory.

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
:+1: This is a much better interface. Please merge.

**Comment by jgillman** [comment]
:+1: Ha, I came here to make the same change only to find someone else already did!

@letsgetrandy Might get merged in faster if you make this into two PRs? One for removing `dl` and another for making the dest folder optional. @jakiestfu might have plans to add more commands alongside `dl`.

**Comment by jakiestfu** [comment]
Thanks homie :100:

**Comment by jakiestfu** [comment]
FYI There was a bug: https://github.com/jakiestfu/off-the-rip/commit/817aff669e4bb9c90f620a74fa4b3bfe01d93ee3

**Pull request merged**
